// AUTO-GENERATED by scripts/gen-api-client.ts -- do not edit by hand.
// Run `npm run gen:api` after adding or renaming an endpoint in src/api/.

import { createCaller } from './caller';

import type { default as _AdminDeleteSubEventEp } from '../api/adminDeleteSubEvent';

type _AdminDeleteSubEventCfg = typeof _AdminDeleteSubEventEp;
export type AdminDeleteSubEventInputType = NonNullable<_AdminDeleteSubEventCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminDeleteSubEventCfg['execute']>[0]['input'];
export type AdminDeleteSubEventOutputType = Awaited<ReturnType<_AdminDeleteSubEventCfg['execute']>>;
export const adminDeleteSubEvent = createCaller<AdminDeleteSubEventInputType, AdminDeleteSubEventOutputType>('adminDeleteSubEvent');

import type { default as _AdminGetDataEp } from '../api/adminGetData';

type _AdminGetDataCfg = typeof _AdminGetDataEp;
export type AdminGetDataInputType = NonNullable<_AdminGetDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetDataCfg['execute']>[0]['input'];
export type AdminGetDataOutputType = Awaited<ReturnType<_AdminGetDataCfg['execute']>>;
export const adminGetData = createCaller<AdminGetDataInputType, AdminGetDataOutputType>('adminGetData');

import type { default as _AdminGetDiagnosticsEp } from '../api/adminGetDiagnostics';

type _AdminGetDiagnosticsCfg = typeof _AdminGetDiagnosticsEp;
export type AdminGetDiagnosticsInputType = NonNullable<_AdminGetDiagnosticsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetDiagnosticsCfg['execute']>[0]['input'];
export type AdminGetDiagnosticsOutputType = Awaited<ReturnType<_AdminGetDiagnosticsCfg['execute']>>;
export const adminGetDiagnostics = createCaller<AdminGetDiagnosticsInputType, AdminGetDiagnosticsOutputType>('adminGetDiagnostics');

import type { default as _AdminGetEmailLogEp } from '../api/adminGetEmailLog';

type _AdminGetEmailLogCfg = typeof _AdminGetEmailLogEp;
export type AdminGetEmailLogInputType = NonNullable<_AdminGetEmailLogCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetEmailLogCfg['execute']>[0]['input'];
export type AdminGetEmailLogOutputType = Awaited<ReturnType<_AdminGetEmailLogCfg['execute']>>;
export const adminGetEmailLog = createCaller<AdminGetEmailLogInputType, AdminGetEmailLogOutputType>('adminGetEmailLog');

import type { default as _AdminGetLiveShowEp } from '../api/adminGetLiveShow';

type _AdminGetLiveShowCfg = typeof _AdminGetLiveShowEp;
export type AdminGetLiveShowInputType = NonNullable<_AdminGetLiveShowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetLiveShowCfg['execute']>[0]['input'];
export type AdminGetLiveShowOutputType = Awaited<ReturnType<_AdminGetLiveShowCfg['execute']>>;
export const adminGetLiveShow = createCaller<AdminGetLiveShowInputType, AdminGetLiveShowOutputType>('adminGetLiveShow');

import type { default as _AdminGetLogsEp } from '../api/adminGetLogs';

type _AdminGetLogsCfg = typeof _AdminGetLogsEp;
export type AdminGetLogsInputType = NonNullable<_AdminGetLogsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetLogsCfg['execute']>[0]['input'];
export type AdminGetLogsOutputType = Awaited<ReturnType<_AdminGetLogsCfg['execute']>>;
export const adminGetLogs = createCaller<AdminGetLogsInputType, AdminGetLogsOutputType>('adminGetLogs');

import type { default as _AdminGetMemberDetailEp } from '../api/adminGetMemberDetail';

type _AdminGetMemberDetailCfg = typeof _AdminGetMemberDetailEp;
export type AdminGetMemberDetailInputType = NonNullable<_AdminGetMemberDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetMemberDetailCfg['execute']>[0]['input'];
export type AdminGetMemberDetailOutputType = Awaited<ReturnType<_AdminGetMemberDetailCfg['execute']>>;
export const adminGetMemberDetail = createCaller<AdminGetMemberDetailInputType, AdminGetMemberDetailOutputType>('adminGetMemberDetail');

import type { default as _AdminGetPresenceEp } from '../api/adminGetPresence';

type _AdminGetPresenceCfg = typeof _AdminGetPresenceEp;
export type AdminGetPresenceInputType = NonNullable<_AdminGetPresenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetPresenceCfg['execute']>[0]['input'];
export type AdminGetPresenceOutputType = Awaited<ReturnType<_AdminGetPresenceCfg['execute']>>;
export const adminGetPresence = createCaller<AdminGetPresenceInputType, AdminGetPresenceOutputType>('adminGetPresence');

import type { default as _AdminGetPresenceHistoryEp } from '../api/adminGetPresenceHistory';

type _AdminGetPresenceHistoryCfg = typeof _AdminGetPresenceHistoryEp;
export type AdminGetPresenceHistoryInputType = NonNullable<_AdminGetPresenceHistoryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetPresenceHistoryCfg['execute']>[0]['input'];
export type AdminGetPresenceHistoryOutputType = Awaited<ReturnType<_AdminGetPresenceHistoryCfg['execute']>>;
export const adminGetPresenceHistory = createCaller<AdminGetPresenceHistoryInputType, AdminGetPresenceHistoryOutputType>('adminGetPresenceHistory');

import type { default as _AdminGetSessionDetailEp } from '../api/adminGetSessionDetail';

type _AdminGetSessionDetailCfg = typeof _AdminGetSessionDetailEp;
export type AdminGetSessionDetailInputType = NonNullable<_AdminGetSessionDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetSessionDetailCfg['execute']>[0]['input'];
export type AdminGetSessionDetailOutputType = Awaited<ReturnType<_AdminGetSessionDetailCfg['execute']>>;
export const adminGetSessionDetail = createCaller<AdminGetSessionDetailInputType, AdminGetSessionDetailOutputType>('adminGetSessionDetail');

import type { default as _AdminGetSupportEp } from '../api/adminGetSupport';

type _AdminGetSupportCfg = typeof _AdminGetSupportEp;
export type AdminGetSupportInputType = NonNullable<_AdminGetSupportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetSupportCfg['execute']>[0]['input'];
export type AdminGetSupportOutputType = Awaited<ReturnType<_AdminGetSupportCfg['execute']>>;
export const adminGetSupport = createCaller<AdminGetSupportInputType, AdminGetSupportOutputType>('adminGetSupport');

import type { default as _AdminGetTicketEp } from '../api/adminGetTicket';

type _AdminGetTicketCfg = typeof _AdminGetTicketEp;
export type AdminGetTicketInputType = NonNullable<_AdminGetTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminGetTicketCfg['execute']>[0]['input'];
export type AdminGetTicketOutputType = Awaited<ReturnType<_AdminGetTicketCfg['execute']>>;
export const adminGetTicket = createCaller<AdminGetTicketInputType, AdminGetTicketOutputType>('adminGetTicket');

import type { default as _AdminLiveShowControlEp } from '../api/adminLiveShowControl';

type _AdminLiveShowControlCfg = typeof _AdminLiveShowControlEp;
export type AdminLiveShowControlInputType = NonNullable<_AdminLiveShowControlCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminLiveShowControlCfg['execute']>[0]['input'];
export type AdminLiveShowControlOutputType = Awaited<ReturnType<_AdminLiveShowControlCfg['execute']>>;
export const adminLiveShowControl = createCaller<AdminLiveShowControlInputType, AdminLiveShowControlOutputType>('adminLiveShowControl');

import type { default as _AdminLiveShowDeviceEp } from '../api/adminLiveShowDevice';

type _AdminLiveShowDeviceCfg = typeof _AdminLiveShowDeviceEp;
export type AdminLiveShowDeviceInputType = NonNullable<_AdminLiveShowDeviceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminLiveShowDeviceCfg['execute']>[0]['input'];
export type AdminLiveShowDeviceOutputType = Awaited<ReturnType<_AdminLiveShowDeviceCfg['execute']>>;
export const adminLiveShowDevice = createCaller<AdminLiveShowDeviceInputType, AdminLiveShowDeviceOutputType>('adminLiveShowDevice');

import type { default as _AdminMoveRoleEp } from '../api/adminMoveRole';

type _AdminMoveRoleCfg = typeof _AdminMoveRoleEp;
export type AdminMoveRoleInputType = NonNullable<_AdminMoveRoleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminMoveRoleCfg['execute']>[0]['input'];
export type AdminMoveRoleOutputType = Awaited<ReturnType<_AdminMoveRoleCfg['execute']>>;
export const adminMoveRole = createCaller<AdminMoveRoleInputType, AdminMoveRoleOutputType>('adminMoveRole');

import type { default as _AdminNoteTicketEp } from '../api/adminNoteTicket';

type _AdminNoteTicketCfg = typeof _AdminNoteTicketEp;
export type AdminNoteTicketInputType = NonNullable<_AdminNoteTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminNoteTicketCfg['execute']>[0]['input'];
export type AdminNoteTicketOutputType = Awaited<ReturnType<_AdminNoteTicketCfg['execute']>>;
export const adminNoteTicket = createCaller<AdminNoteTicketInputType, AdminNoteTicketOutputType>('adminNoteTicket');

import type { default as _AdminRecomputeAttendanceEp } from '../api/adminRecomputeAttendance';

type _AdminRecomputeAttendanceCfg = typeof _AdminRecomputeAttendanceEp;
export type AdminRecomputeAttendanceInputType = NonNullable<_AdminRecomputeAttendanceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminRecomputeAttendanceCfg['execute']>[0]['input'];
export type AdminRecomputeAttendanceOutputType = Awaited<ReturnType<_AdminRecomputeAttendanceCfg['execute']>>;
export const adminRecomputeAttendance = createCaller<AdminRecomputeAttendanceInputType, AdminRecomputeAttendanceOutputType>('adminRecomputeAttendance');

import type { default as _AdminRemindMaintainersEp } from '../api/adminRemindMaintainers';

type _AdminRemindMaintainersCfg = typeof _AdminRemindMaintainersEp;
export type AdminRemindMaintainersInputType = NonNullable<_AdminRemindMaintainersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminRemindMaintainersCfg['execute']>[0]['input'];
export type AdminRemindMaintainersOutputType = Awaited<ReturnType<_AdminRemindMaintainersCfg['execute']>>;
export const adminRemindMaintainers = createCaller<AdminRemindMaintainersInputType, AdminRemindMaintainersOutputType>('adminRemindMaintainers');

import type { default as _AdminReplyTicketEp } from '../api/adminReplyTicket';

type _AdminReplyTicketCfg = typeof _AdminReplyTicketEp;
export type AdminReplyTicketInputType = NonNullable<_AdminReplyTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminReplyTicketCfg['execute']>[0]['input'];
export type AdminReplyTicketOutputType = Awaited<ReturnType<_AdminReplyTicketCfg['execute']>>;
export const adminReplyTicket = createCaller<AdminReplyTicketInputType, AdminReplyTicketOutputType>('adminReplyTicket');

import type { default as _AdminSaveLiveShowEp } from '../api/adminSaveLiveShow';

type _AdminSaveLiveShowCfg = typeof _AdminSaveLiveShowEp;
export type AdminSaveLiveShowInputType = NonNullable<_AdminSaveLiveShowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveLiveShowCfg['execute']>[0]['input'];
export type AdminSaveLiveShowOutputType = Awaited<ReturnType<_AdminSaveLiveShowCfg['execute']>>;
export const adminSaveLiveShow = createCaller<AdminSaveLiveShowInputType, AdminSaveLiveShowOutputType>('adminSaveLiveShow');

import type { default as _AdminSaveLiveShowScenesEp } from '../api/adminSaveLiveShowScenes';

type _AdminSaveLiveShowScenesCfg = typeof _AdminSaveLiveShowScenesEp;
export type AdminSaveLiveShowScenesInputType = NonNullable<_AdminSaveLiveShowScenesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveLiveShowScenesCfg['execute']>[0]['input'];
export type AdminSaveLiveShowScenesOutputType = Awaited<ReturnType<_AdminSaveLiveShowScenesCfg['execute']>>;
export const adminSaveLiveShowScenes = createCaller<AdminSaveLiveShowScenesInputType, AdminSaveLiveShowScenesOutputType>('adminSaveLiveShowScenes');

import type { default as _AdminSaveMemberEp } from '../api/adminSaveMember';

type _AdminSaveMemberCfg = typeof _AdminSaveMemberEp;
export type AdminSaveMemberInputType = NonNullable<_AdminSaveMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveMemberCfg['execute']>[0]['input'];
export type AdminSaveMemberOutputType = Awaited<ReturnType<_AdminSaveMemberCfg['execute']>>;
export const adminSaveMember = createCaller<AdminSaveMemberInputType, AdminSaveMemberOutputType>('adminSaveMember');

import type { default as _AdminSaveShowEp } from '../api/adminSaveShow';

type _AdminSaveShowCfg = typeof _AdminSaveShowEp;
export type AdminSaveShowInputType = NonNullable<_AdminSaveShowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveShowCfg['execute']>[0]['input'];
export type AdminSaveShowOutputType = Awaited<ReturnType<_AdminSaveShowCfg['execute']>>;
export const adminSaveShow = createCaller<AdminSaveShowInputType, AdminSaveShowOutputType>('adminSaveShow');

import type { default as _AdminSaveSubEventEp } from '../api/adminSaveSubEvent';

type _AdminSaveSubEventCfg = typeof _AdminSaveSubEventEp;
export type AdminSaveSubEventInputType = NonNullable<_AdminSaveSubEventCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveSubEventCfg['execute']>[0]['input'];
export type AdminSaveSubEventOutputType = Awaited<ReturnType<_AdminSaveSubEventCfg['execute']>>;
export const adminSaveSubEvent = createCaller<AdminSaveSubEventInputType, AdminSaveSubEventOutputType>('adminSaveSubEvent');

import type { default as _AdminSendMessageEp } from '../api/adminSendMessage';

type _AdminSendMessageCfg = typeof _AdminSendMessageEp;
export type AdminSendMessageInputType = NonNullable<_AdminSendMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSendMessageCfg['execute']>[0]['input'];
export type AdminSendMessageOutputType = Awaited<ReturnType<_AdminSendMessageCfg['execute']>>;
export const adminSendMessage = createCaller<AdminSendMessageInputType, AdminSendMessageOutputType>('adminSendMessage');

import type { default as _AdminSendReminderEp } from '../api/adminSendReminder';

type _AdminSendReminderCfg = typeof _AdminSendReminderEp;
export type AdminSendReminderInputType = NonNullable<_AdminSendReminderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSendReminderCfg['execute']>[0]['input'];
export type AdminSendReminderOutputType = Awaited<ReturnType<_AdminSendReminderCfg['execute']>>;
export const adminSendReminder = createCaller<AdminSendReminderInputType, AdminSendReminderOutputType>('adminSendReminder');

import type { default as _AdminSetMaintainerEp } from '../api/adminSetMaintainer';

type _AdminSetMaintainerCfg = typeof _AdminSetMaintainerEp;
export type AdminSetMaintainerInputType = NonNullable<_AdminSetMaintainerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSetMaintainerCfg['execute']>[0]['input'];
export type AdminSetMaintainerOutputType = Awaited<ReturnType<_AdminSetMaintainerCfg['execute']>>;
export const adminSetMaintainer = createCaller<AdminSetMaintainerInputType, AdminSetMaintainerOutputType>('adminSetMaintainer');

import type { default as _AdminUpdateTicketEp } from '../api/adminUpdateTicket';

type _AdminUpdateTicketCfg = typeof _AdminUpdateTicketEp;
export type AdminUpdateTicketInputType = NonNullable<_AdminUpdateTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminUpdateTicketCfg['execute']>[0]['input'];
export type AdminUpdateTicketOutputType = Awaited<ReturnType<_AdminUpdateTicketCfg['execute']>>;
export const adminUpdateTicket = createCaller<AdminUpdateTicketInputType, AdminUpdateTicketOutputType>('adminUpdateTicket');

import type { default as _CheckEmailEp } from '../api/checkEmail';

type _CheckEmailCfg = typeof _CheckEmailEp;
export type CheckEmailInputType = NonNullable<_CheckEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CheckEmailCfg['execute']>[0]['input'];
export type CheckEmailOutputType = Awaited<ReturnType<_CheckEmailCfg['execute']>>;
export const checkEmail = createCaller<CheckEmailInputType, CheckEmailOutputType>('checkEmail');

import type { default as _DeletePushSubscriptionEp } from '../api/deletePushSubscription';

type _DeletePushSubscriptionCfg = typeof _DeletePushSubscriptionEp;
export type DeletePushSubscriptionInputType = NonNullable<_DeletePushSubscriptionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeletePushSubscriptionCfg['execute']>[0]['input'];
export type DeletePushSubscriptionOutputType = Awaited<ReturnType<_DeletePushSubscriptionCfg['execute']>>;
export const deletePushSubscription = createCaller<DeletePushSubscriptionInputType, DeletePushSubscriptionOutputType>('deletePushSubscription');

import type { default as _EnableLiveShowDeviceEp } from '../api/enableLiveShowDevice';

type _EnableLiveShowDeviceCfg = typeof _EnableLiveShowDeviceEp;
export type EnableLiveShowDeviceInputType = NonNullable<_EnableLiveShowDeviceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_EnableLiveShowDeviceCfg['execute']>[0]['input'];
export type EnableLiveShowDeviceOutputType = Awaited<ReturnType<_EnableLiveShowDeviceCfg['execute']>>;
export const enableLiveShowDevice = createCaller<EnableLiveShowDeviceInputType, EnableLiveShowDeviceOutputType>('enableLiveShowDevice');

import type { default as _GetCalendarEp } from '../api/getCalendar';

type _GetCalendarCfg = typeof _GetCalendarEp;
export type GetCalendarInputType = NonNullable<_GetCalendarCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCalendarCfg['execute']>[0]['input'];
export type GetCalendarOutputType = Awaited<ReturnType<_GetCalendarCfg['execute']>>;
export const getCalendar = createCaller<GetCalendarInputType, GetCalendarOutputType>('getCalendar');

import type { default as _GetCalendarFeedEp } from '../api/getCalendarFeed';

type _GetCalendarFeedCfg = typeof _GetCalendarFeedEp;
export type GetCalendarFeedInputType = NonNullable<_GetCalendarFeedCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCalendarFeedCfg['execute']>[0]['input'];
export type GetCalendarFeedOutputType = Awaited<ReturnType<_GetCalendarFeedCfg['execute']>>;
export const getCalendarFeed = createCaller<GetCalendarFeedInputType, GetCalendarFeedOutputType>('getCalendarFeed');

import type { default as _GetCatLoginAdminsEp } from '../api/getCatLoginAdmins';

type _GetCatLoginAdminsCfg = typeof _GetCatLoginAdminsEp;
export type GetCatLoginAdminsInputType = NonNullable<_GetCatLoginAdminsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCatLoginAdminsCfg['execute']>[0]['input'];
export type GetCatLoginAdminsOutputType = Awaited<ReturnType<_GetCatLoginAdminsCfg['execute']>>;
export const getCatLoginAdmins = createCaller<GetCatLoginAdminsInputType, GetCatLoginAdminsOutputType>('getCatLoginAdmins');

import type { default as _GetLiveShowAdminsEp } from '../api/getLiveShowAdmins';

type _GetLiveShowAdminsCfg = typeof _GetLiveShowAdminsEp;
export type GetLiveShowAdminsInputType = NonNullable<_GetLiveShowAdminsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLiveShowAdminsCfg['execute']>[0]['input'];
export type GetLiveShowAdminsOutputType = Awaited<ReturnType<_GetLiveShowAdminsCfg['execute']>>;
export const getLiveShowAdmins = createCaller<GetLiveShowAdminsInputType, GetLiveShowAdminsOutputType>('getLiveShowAdmins');

import type { default as _GetLiveShowStateEp } from '../api/getLiveShowState';

type _GetLiveShowStateCfg = typeof _GetLiveShowStateEp;
export type GetLiveShowStateInputType = NonNullable<_GetLiveShowStateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLiveShowStateCfg['execute']>[0]['input'];
export type GetLiveShowStateOutputType = Awaited<ReturnType<_GetLiveShowStateCfg['execute']>>;
export const getLiveShowState = createCaller<GetLiveShowStateInputType, GetLiveShowStateOutputType>('getLiveShowState');

import type { default as _GetMeEp } from '../api/getMe';

type _GetMeCfg = typeof _GetMeEp;
export type GetMeInputType = NonNullable<_GetMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeCfg['execute']>[0]['input'];
export type GetMeOutputType = Awaited<ReturnType<_GetMeCfg['execute']>>;
export const getMe = createCaller<GetMeInputType, GetMeOutputType>('getMe');

import type { default as _GetMyCatLoginStatusEp } from '../api/getMyCatLoginStatus';

type _GetMyCatLoginStatusCfg = typeof _GetMyCatLoginStatusEp;
export type GetMyCatLoginStatusInputType = NonNullable<_GetMyCatLoginStatusCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMyCatLoginStatusCfg['execute']>[0]['input'];
export type GetMyCatLoginStatusOutputType = Awaited<ReturnType<_GetMyCatLoginStatusCfg['execute']>>;
export const getMyCatLoginStatus = createCaller<GetMyCatLoginStatusInputType, GetMyCatLoginStatusOutputType>('getMyCatLoginStatus');

import type { default as _GetMyEventsEp } from '../api/getMyEvents';

type _GetMyEventsCfg = typeof _GetMyEventsEp;
export type GetMyEventsInputType = NonNullable<_GetMyEventsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMyEventsCfg['execute']>[0]['input'];
export type GetMyEventsOutputType = Awaited<ReturnType<_GetMyEventsCfg['execute']>>;
export const getMyEvents = createCaller<GetMyEventsInputType, GetMyEventsOutputType>('getMyEvents');

import type { default as _GetPresenceEp } from '../api/getPresence';

type _GetPresenceCfg = typeof _GetPresenceEp;
export type GetPresenceInputType = NonNullable<_GetPresenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPresenceCfg['execute']>[0]['input'];
export type GetPresenceOutputType = Awaited<ReturnType<_GetPresenceCfg['execute']>>;
export const getPresence = createCaller<GetPresenceInputType, GetPresenceOutputType>('getPresence');

import type { default as _GetPublicCalendarEp } from '../api/getPublicCalendar';

type _GetPublicCalendarCfg = typeof _GetPublicCalendarEp;
export type GetPublicCalendarInputType = NonNullable<_GetPublicCalendarCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicCalendarCfg['execute']>[0]['input'];
export type GetPublicCalendarOutputType = Awaited<ReturnType<_GetPublicCalendarCfg['execute']>>;
export const getPublicCalendar = createCaller<GetPublicCalendarInputType, GetPublicCalendarOutputType>('getPublicCalendar');

import type { default as _GetPublicParentsEp } from '../api/getPublicParents';

type _GetPublicParentsCfg = typeof _GetPublicParentsEp;
export type GetPublicParentsInputType = NonNullable<_GetPublicParentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicParentsCfg['execute']>[0]['input'];
export type GetPublicParentsOutputType = Awaited<ReturnType<_GetPublicParentsCfg['execute']>>;
export const getPublicParents = createCaller<GetPublicParentsInputType, GetPublicParentsOutputType>('getPublicParents');

import type { default as _GetPushConfigEp } from '../api/getPushConfig';

type _GetPushConfigCfg = typeof _GetPushConfigEp;
export type GetPushConfigInputType = NonNullable<_GetPushConfigCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPushConfigCfg['execute']>[0]['input'];
export type GetPushConfigOutputType = Awaited<ReturnType<_GetPushConfigCfg['execute']>>;
export const getPushConfig = createCaller<GetPushConfigInputType, GetPushConfigOutputType>('getPushConfig');

import type { default as _GetStaffHomeEp } from '../api/getStaffHome';

type _GetStaffHomeCfg = typeof _GetStaffHomeEp;
export type GetStaffHomeInputType = NonNullable<_GetStaffHomeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetStaffHomeCfg['execute']>[0]['input'];
export type GetStaffHomeOutputType = Awaited<ReturnType<_GetStaffHomeCfg['execute']>>;
export const getStaffHome = createCaller<GetStaffHomeInputType, GetStaffHomeOutputType>('getStaffHome');

import type { default as _GetStageLayoutEp } from '../api/getStageLayout';

type _GetStageLayoutCfg = typeof _GetStageLayoutEp;
export type GetStageLayoutInputType = NonNullable<_GetStageLayoutCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetStageLayoutCfg['execute']>[0]['input'];
export type GetStageLayoutOutputType = Awaited<ReturnType<_GetStageLayoutCfg['execute']>>;
export const getStageLayout = createCaller<GetStageLayoutInputType, GetStageLayoutOutputType>('getStageLayout');

import type { default as _LiveShowAnnouncementEp } from '../api/liveShowAnnouncement';

type _LiveShowAnnouncementCfg = typeof _LiveShowAnnouncementEp;
export type LiveShowAnnouncementInputType = NonNullable<_LiveShowAnnouncementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LiveShowAnnouncementCfg['execute']>[0]['input'];
export type LiveShowAnnouncementOutputType = Awaited<ReturnType<_LiveShowAnnouncementCfg['execute']>>;
export const liveShowAnnouncement = createCaller<LiveShowAnnouncementInputType, LiveShowAnnouncementOutputType>('liveShowAnnouncement');

import type { default as _LiveShowChatEp } from '../api/liveShowChat';

type _LiveShowChatCfg = typeof _LiveShowChatEp;
export type LiveShowChatInputType = NonNullable<_LiveShowChatCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LiveShowChatCfg['execute']>[0]['input'];
export type LiveShowChatOutputType = Awaited<ReturnType<_LiveShowChatCfg['execute']>>;
export const liveShowChat = createCaller<LiveShowChatInputType, LiveShowChatOutputType>('liveShowChat');

import type { default as _LiveShowMovementEp } from '../api/liveShowMovement';

type _LiveShowMovementCfg = typeof _LiveShowMovementEp;
export type LiveShowMovementInputType = NonNullable<_LiveShowMovementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LiveShowMovementCfg['execute']>[0]['input'];
export type LiveShowMovementOutputType = Awaited<ReturnType<_LiveShowMovementCfg['execute']>>;
export const liveShowMovement = createCaller<LiveShowMovementInputType, LiveShowMovementOutputType>('liveShowMovement');

import type { default as _LiveShowUnlockAdminEp } from '../api/liveShowUnlockAdmin';

type _LiveShowUnlockAdminCfg = typeof _LiveShowUnlockAdminEp;
export type LiveShowUnlockAdminInputType = NonNullable<_LiveShowUnlockAdminCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LiveShowUnlockAdminCfg['execute']>[0]['input'];
export type LiveShowUnlockAdminOutputType = Awaited<ReturnType<_LiveShowUnlockAdminCfg['execute']>>;
export const liveShowUnlockAdmin = createCaller<LiveShowUnlockAdminInputType, LiveShowUnlockAdminOutputType>('liveShowUnlockAdmin');

import type { default as _MemberEditTicketEp } from '../api/memberEditTicket';

type _MemberEditTicketCfg = typeof _MemberEditTicketEp;
export type MemberEditTicketInputType = NonNullable<_MemberEditTicketCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MemberEditTicketCfg['execute']>[0]['input'];
export type MemberEditTicketOutputType = Awaited<ReturnType<_MemberEditTicketCfg['execute']>>;
export const memberEditTicket = createCaller<MemberEditTicketInputType, MemberEditTicketOutputType>('memberEditTicket');

import type { default as _MemberGetMyTicketsEp } from '../api/memberGetMyTickets';

type _MemberGetMyTicketsCfg = typeof _MemberGetMyTicketsEp;
export type MemberGetMyTicketsInputType = NonNullable<_MemberGetMyTicketsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MemberGetMyTicketsCfg['execute']>[0]['input'];
export type MemberGetMyTicketsOutputType = Awaited<ReturnType<_MemberGetMyTicketsCfg['execute']>>;
export const memberGetMyTickets = createCaller<MemberGetMyTicketsInputType, MemberGetMyTicketsOutputType>('memberGetMyTickets');

import type { default as _NotificationPassEp } from '../api/notificationPass';

type _NotificationPassCfg = typeof _NotificationPassEp;
export type NotificationPassInputType = NonNullable<_NotificationPassCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_NotificationPassCfg['execute']>[0]['input'];
export type NotificationPassOutputType = Awaited<ReturnType<_NotificationPassCfg['execute']>>;
export const notificationPass = createCaller<NotificationPassInputType, NotificationPassOutputType>('notificationPass');

import type { default as _PresenceApprovalEp } from '../api/presenceApproval';

type _PresenceApprovalCfg = typeof _PresenceApprovalEp;
export type PresenceApprovalInputType = NonNullable<_PresenceApprovalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceApprovalCfg['execute']>[0]['input'];
export type PresenceApprovalOutputType = Awaited<ReturnType<_PresenceApprovalCfg['execute']>>;
export const presenceApproval = createCaller<PresenceApprovalInputType, PresenceApprovalOutputType>('presenceApproval');

import type { default as _PresenceDecisionEp } from '../api/presenceDecision';

type _PresenceDecisionCfg = typeof _PresenceDecisionEp;
export type PresenceDecisionInputType = NonNullable<_PresenceDecisionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceDecisionCfg['execute']>[0]['input'];
export type PresenceDecisionOutputType = Awaited<ReturnType<_PresenceDecisionCfg['execute']>>;
export const presenceDecision = createCaller<PresenceDecisionInputType, PresenceDecisionOutputType>('presenceDecision');

import type { default as _PresenceEndEp } from '../api/presenceEnd';

type _PresenceEndCfg = typeof _PresenceEndEp;
export type PresenceEndInputType = NonNullable<_PresenceEndCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceEndCfg['execute']>[0]['input'];
export type PresenceEndOutputType = Awaited<ReturnType<_PresenceEndCfg['execute']>>;
export const presenceEnd = createCaller<PresenceEndInputType, PresenceEndOutputType>('presenceEnd');

import type { default as _PresenceRequestEp } from '../api/presenceRequest';

type _PresenceRequestCfg = typeof _PresenceRequestEp;
export type PresenceRequestInputType = NonNullable<_PresenceRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceRequestCfg['execute']>[0]['input'];
export type PresenceRequestOutputType = Awaited<ReturnType<_PresenceRequestCfg['execute']>>;
export const presenceRequest = createCaller<PresenceRequestInputType, PresenceRequestOutputType>('presenceRequest');

import type { default as _PresenceStartEp } from '../api/presenceStart';

type _PresenceStartCfg = typeof _PresenceStartEp;
export type PresenceStartInputType = NonNullable<_PresenceStartCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PresenceStartCfg['execute']>[0]['input'];
export type PresenceStartOutputType = Awaited<ReturnType<_PresenceStartCfg['execute']>>;
export const presenceStart = createCaller<PresenceStartInputType, PresenceStartOutputType>('presenceStart');

import type { default as _SaveLiveShowScriptEp } from '../api/saveLiveShowScript';

type _SaveLiveShowScriptCfg = typeof _SaveLiveShowScriptEp;
export type SaveLiveShowScriptInputType = NonNullable<_SaveLiveShowScriptCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveLiveShowScriptCfg['execute']>[0]['input'];
export type SaveLiveShowScriptOutputType = Awaited<ReturnType<_SaveLiveShowScriptCfg['execute']>>;
export const saveLiveShowScript = createCaller<SaveLiveShowScriptInputType, SaveLiveShowScriptOutputType>('saveLiveShowScript');

import type { default as _SavePushSubscriptionEp } from '../api/savePushSubscription';

type _SavePushSubscriptionCfg = typeof _SavePushSubscriptionEp;
export type SavePushSubscriptionInputType = NonNullable<_SavePushSubscriptionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePushSubscriptionCfg['execute']>[0]['input'];
export type SavePushSubscriptionOutputType = Awaited<ReturnType<_SavePushSubscriptionCfg['execute']>>;
export const savePushSubscription = createCaller<SavePushSubscriptionInputType, SavePushSubscriptionOutputType>('savePushSubscription');

import type { default as _SendTestNotificationEp } from '../api/sendTestNotification';

type _SendTestNotificationCfg = typeof _SendTestNotificationEp;
export type SendTestNotificationInputType = NonNullable<_SendTestNotificationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendTestNotificationCfg['execute']>[0]['input'];
export type SendTestNotificationOutputType = Awaited<ReturnType<_SendTestNotificationCfg['execute']>>;
export const sendTestNotification = createCaller<SendTestNotificationInputType, SendTestNotificationOutputType>('sendTestNotification');

import type { default as _SetAdminNotificationsEp } from '../api/setAdminNotifications';

type _SetAdminNotificationsCfg = typeof _SetAdminNotificationsEp;
export type SetAdminNotificationsInputType = NonNullable<_SetAdminNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetAdminNotificationsCfg['execute']>[0]['input'];
export type SetAdminNotificationsOutputType = Awaited<ReturnType<_SetAdminNotificationsCfg['execute']>>;
export const setAdminNotifications = createCaller<SetAdminNotificationsInputType, SetAdminNotificationsOutputType>('setAdminNotifications');

import type { default as _SetAttendanceEp } from '../api/setAttendance';

type _SetAttendanceCfg = typeof _SetAttendanceEp;
export type SetAttendanceInputType = NonNullable<_SetAttendanceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetAttendanceCfg['execute']>[0]['input'];
export type SetAttendanceOutputType = Awaited<ReturnType<_SetAttendanceCfg['execute']>>;
export const setAttendance = createCaller<SetAttendanceInputType, SetAttendanceOutputType>('setAttendance');

import type { default as _SetMyAdminSecretEp } from '../api/setMyAdminSecret';

type _SetMyAdminSecretCfg = typeof _SetMyAdminSecretEp;
export type SetMyAdminSecretInputType = NonNullable<_SetMyAdminSecretCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetMyAdminSecretCfg['execute']>[0]['input'];
export type SetMyAdminSecretOutputType = Awaited<ReturnType<_SetMyAdminSecretCfg['execute']>>;
export const setMyAdminSecret = createCaller<SetMyAdminSecretInputType, SetMyAdminSecretOutputType>('setMyAdminSecret');

import type { default as _SetShowResponseEp } from '../api/setShowResponse';

type _SetShowResponseCfg = typeof _SetShowResponseEp;
export type SetShowResponseInputType = NonNullable<_SetShowResponseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetShowResponseCfg['execute']>[0]['input'];
export type SetShowResponseOutputType = Awaited<ReturnType<_SetShowResponseCfg['execute']>>;
export const setShowResponse = createCaller<SetShowResponseInputType, SetShowResponseOutputType>('setShowResponse');

import type { default as _SubmitSupportEp } from '../api/submitSupport';

type _SubmitSupportCfg = typeof _SubmitSupportEp;
export type SubmitSupportInputType = NonNullable<_SubmitSupportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitSupportCfg['execute']>[0]['input'];
export type SubmitSupportOutputType = Awaited<ReturnType<_SubmitSupportCfg['execute']>>;
export const submitSupport = createCaller<SubmitSupportInputType, SubmitSupportOutputType>('submitSupport');

import type { default as _SupportEscalateEp } from '../api/supportEscalate';

type _SupportEscalateCfg = typeof _SupportEscalateEp;
export type SupportEscalateInputType = NonNullable<_SupportEscalateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SupportEscalateCfg['execute']>[0]['input'];
export type SupportEscalateOutputType = Awaited<ReturnType<_SupportEscalateCfg['execute']>>;
export const supportEscalate = createCaller<SupportEscalateInputType, SupportEscalateOutputType>('supportEscalate');

import type { default as _UpdateMyProfileEp } from '../api/updateMyProfile';

type _UpdateMyProfileCfg = typeof _UpdateMyProfileEp;
export type UpdateMyProfileInputType = NonNullable<_UpdateMyProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateMyProfileCfg['execute']>[0]['input'];
export type UpdateMyProfileOutputType = Awaited<ReturnType<_UpdateMyProfileCfg['execute']>>;
export const updateMyProfile = createCaller<UpdateMyProfileInputType, UpdateMyProfileOutputType>('updateMyProfile');
// SPA analytics beacons: these are plain routes in server/index.ts (not zod
// endpoints, so they never appear in the api/ folder), emitted by hand here.

export type AnalyticsViewInputType = { viewId: string; path: string; referer?: string };
export type AnalyticsViewOutputType = { ok: boolean };
export const analyticsView = createCaller<AnalyticsViewInputType, AnalyticsViewOutputType>('analyticsView');

export type AnalyticsLeaveInputType = { viewId: string; path: string };
export type AnalyticsLeaveOutputType = { ok: boolean };
export const analyticsLeave = createCaller<AnalyticsLeaveInputType, AnalyticsLeaveOutputType>('analyticsLeave');

/** Namespace object, kept for parity with the original generated client. */
export const api = {
  adminDeleteSubEvent,
  adminGetData,
  adminGetDiagnostics,
  adminGetEmailLog,
  adminGetLiveShow,
  adminGetLogs,
  adminGetMemberDetail,
  adminGetPresence,
  adminGetPresenceHistory,
  adminGetSessionDetail,
  adminGetSupport,
  adminGetTicket,
  adminLiveShowControl,
  adminLiveShowDevice,
  adminMoveRole,
  adminNoteTicket,
  adminRecomputeAttendance,
  adminRemindMaintainers,
  adminReplyTicket,
  adminSaveLiveShow,
  adminSaveLiveShowScenes,
  adminSaveMember,
  adminSaveShow,
  adminSaveSubEvent,
  adminSendMessage,
  adminSendReminder,
  adminSetMaintainer,
  adminUpdateTicket,
  checkEmail,
  deletePushSubscription,
  enableLiveShowDevice,
  getCalendar,
  getCalendarFeed,
  getCatLoginAdmins,
  getLiveShowAdmins,
  getLiveShowState,
  getMe,
  getMyCatLoginStatus,
  getMyEvents,
  getPresence,
  getPublicCalendar,
  getPublicParents,
  getPushConfig,
  getStaffHome,
  getStageLayout,
  liveShowAnnouncement,
  liveShowChat,
  liveShowMovement,
  liveShowUnlockAdmin,
  memberEditTicket,
  memberGetMyTickets,
  notificationPass,
  presenceApproval,
  presenceDecision,
  presenceEnd,
  presenceRequest,
  presenceStart,
  saveLiveShowScript,
  savePushSubscription,
  sendTestNotification,
  setAdminNotifications,
  setAttendance,
  setMyAdminSecret,
  setShowResponse,
  submitSupport,
  supportEscalate,
  updateMyProfile,
  analyticsLeave,
  analyticsView,
};
