/**
 * Generates src/lib/api.ts from the endpoint files in src/api/.
 *
 * The original .zite/api.ts was a purely mechanical projection of those files:
 * for each endpoint it derived Input/Output types off the config object and
 * wrapped the name in createCaller. Deriving the types the same way means every
 * existing `import type { GetMeOutputType } from ...` in the app keeps working
 * unchanged, and adding an endpoint is just adding a file and re-running this.
 *
 * Run: npm run gen:api
 */

import { readdirSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const apiDir = path.join(root, 'src', 'api');

const pascal = (name: string) => name.charAt(0).toUpperCase() + name.slice(1);

const files = readdirSync(apiDir)
  .filter((f) => f.endsWith('.ts'))
  .sort();

const header = `// AUTO-GENERATED by scripts/gen-api-client.ts -- do not edit by hand.
// Run \`npm run gen:api\` after adding or renaming an endpoint in src/api/.

import { createCaller } from './caller';
`;

const body = files
  .map((file) => {
    const endpoint = path.basename(file, '.ts');
    const T = pascal(endpoint);
    return `import type { default as _${T}Ep } from '../api/${endpoint}';

type _${T}Cfg = typeof _${T}Ep;
export type ${T}InputType = NonNullable<_${T}Cfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_${T}Cfg['execute']>[0]['input'];
export type ${T}OutputType = Awaited<ReturnType<_${T}Cfg['execute']>>;
export const ${endpoint} = createCaller<${T}InputType, ${T}OutputType>('${endpoint}');`;
  })
  .join('\n\n');

const extras = `// SPA analytics beacons: these are plain routes in server/index.ts (not zod
// endpoints, so they never appear in the api/ folder), emitted by hand here.

export type AnalyticsViewInputType = { viewId: string; path: string; referer?: string };
export type AnalyticsViewOutputType = { ok: boolean };
export const analyticsView = createCaller<AnalyticsViewInputType, AnalyticsViewOutputType>('analyticsView');

export type AnalyticsLeaveInputType = { viewId: string; path: string };
export type AnalyticsLeaveOutputType = { ok: boolean };
export const analyticsLeave = createCaller<AnalyticsLeaveInputType, AnalyticsLeaveOutputType>('analyticsLeave');`;

const ns = [
  ...files.map((f) => `  ${path.basename(f, '.ts')},`),
  '  analyticsLeave,',
  '  analyticsView,',
].join('\n');

writeFileSync(
  path.join(root, 'src', 'lib', 'api.ts'),
  `${header}\n${body}\n${extras}\n\n/** Namespace object, kept for parity with the original generated client. */\nexport const api = {\n${ns}\n};\n`
);
console.log(`src/lib/api.ts: ${files.length} endpoints`);